### ISSUE TITLE
Flash messages not displayed in blade

### ISSUE THREAD

**Issue by krisc78** [php-flasher/php-flasher#138]
I'm using Laravel 10.  I've installed the package via "composer require php-flasher/flasher-laravel"
Now I'm able to fire flash messages in my controller. I see them in the session data (in flasher::envelopes).
But they aren't showing up in my views. In my config file I have 'auto_render' => true.
If I put @flasher_render in my blade view, the only thing that's happens is, a notification to warn that this method wil be deprecated.

How can I fix this? I really like to use this package ;-)

**Comment by yoeunes** [comment]
Hello @krisc78, thanks for reporting the issue.
Can you share some code on GitHub where I can reproduce the issue?

**Comment by krisc78** [comment]
This is a part of my composer.json:

```
    "require": {
        "php": "^8.1",
        "barryvdh/laravel-dompdf": "^2.0",
        "guzzlehttp/guzzle": "^7.0.1",
        "kalnoy/nestedset": "^6.0",
        "laravel/framework": "^10.0",
        "laravel/sanctum": "^3.2",
        "laravel/tinker": "^2.5",
        "livewire/livewire": "^2.11",
        "maatwebsite/excel": "^3.1",
        "php-flasher/flasher-laravel": "^1.13",
        "php-flasher/flasher-toastr-laravel": "^1.13",
        "spatie/laravel-view-models": "^1.5",
        "stancl/tenancy": "^3.7",
        "staudenmeir/eloquent-has-many-deep": "^1.7"
    },
    "require-dev": {
        "barryvdh/laravel-debugbar": "^3.7",
        "fakerphp/faker": "^1.9.1",
        "laravel-lang/lang": "^12.17",
        "laravel/breeze": "^1.14",
        "laravel/pint": "^1.5",
        "laravel/sail": "^1.0.1",
        "mockery/mockery": "^1.4.4",
        "nunomaduro/collision": "^7.0",
        "phpunit/phpunit": "^10.0",
        "spatie/laravel-ignition": "^2.0"
    },
```
This is my controller method:

```
   <?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Imports\TargetsImport;
use Illuminate\Http\Request;
use Maatwebsite\Excel\Facades\Excel;

class TargetController extends Controller
....
 public function import()
    {
        toastr()->addInfo('Heads up: This may take a while.');
        return view('admin.targets.import');
    }
```
This is all working, following image is showing my session data:
<img width="994" alt="image" src="https://user-images.githubusercontent.com/9980518/224063758-ac756dc0-4d1b-4dcd-95dd-82c73fde728e.png">

My view is extendig a master view:
```
@extends('layouts.master', ['title' => 'Periods'])

@section('workspace')

        <!-- Breadcrumb -->
        <section class="breadcrumb">
```
It's like nothing is injected in my views...? How can I force to show the data? Or extend this package to show the data?

**Comment by Paul-Olohan** [comment]
I had the same issue and only resolved the injection by manually adding this entry to the middleware array in Kernel.php.

`protected $middleware = [
        \Flasher\Laravel\Middleware\FlasherMiddleware::class,
         ]`

**Comment by yusofsf** [comment]
> This is a part of my composer.json:
> 
> ```
>     "require": {
>         "php": "^8.1",
>         "barryvdh/laravel-dompdf": "^2.0",
>         "guzzlehttp/guzzle": "^7.0.1",
>         "kalnoy/nestedset": "^6.0",
>         "laravel/framework": "^10.0",
>         "laravel/sanctum": "^3.2",
>         "laravel/tinker": "^2.5",
>         "livewire/livewire": "^2.11",
>         "maatwebsite/excel": "^3.1",
>         "php-flasher/flasher-laravel": "^1.13",
>         "php-flasher/flasher-toastr-laravel": "^1.13",
>         "spatie/laravel-view-models": "^1.5",
>         "stancl/tenancy": "^3.7",
>         "staudenmeir/eloquent-has-many-deep": "^1.7"
>     },
>     "require-dev": {
>         "barryvdh/laravel-debugbar": "^3.7",
>         "fakerphp/faker": "^1.9.1",
>         "laravel-lang/lang": "^12.17",
>         "laravel/breeze": "^1.14",
>         "laravel/pint": "^1.5",
>         "laravel/sail": "^1.0.1",
>         "mockery/mockery": "^1.4.4",
>         "nunomaduro/collision": "^7.0",
>         "phpunit/phpunit": "^10.0",
>         "spatie/laravel-ignition": "^2.0"
>     },
> ```
> 
> This is my controller method:
> 
> ```
>    <?php
> 
> namespace App\Http\Controllers\Admin;
> 
> use App\Http\Controllers\Controller;
> use App\Imports\TargetsImport;
> use Illuminate\Http\Request;
> use Maatwebsite\Excel\Facades\Excel;
> 
> class TargetController extends Controller
> ....
>  public function import()
>     {
>         toastr()->addInfo('Heads up: This may take a while.');
>         return view('admin.targets.import');
>     }
> ```
> 
> This is all working, following image is showing my session data: <img alt="image" width="994" src="https://user-images.githubusercontent.com/9980518/224063758-ac756dc0-4d1b-4dcd-95dd-82c73fde728e.png">
> 
> My view is extendig a master view:
> 
> ```
> @extends('layouts.master', ['title' => 'Periods'])
> 
> @section('workspace')
> 
>         
>         <section class="breadcrumb">
> ```
> 
> It's like nothing is injected in my views...? How can I force to show the data? Or extend this package to show the data?

I think the issue is you show flasher and immediately refresh the page and redirect user to another page
if you could add timer to show the flasher then redirect to another page this issue wont happen

although i think it would be good idea for this package when user call it, stops laravel application until the flasher does his jobs
its up to contributers to discuss and agree on that

**Comment by nkhoangvu** [comment]
I also had the same issue but adding below entry to the middleware array in Kernel.php:

protected $middleware = [ \Flasher\Laravel\Middleware\FlasherMiddleware::class, ]

cause the flash notifications keep displaying anytime, anywhere in my app. Moreover, the old notification are not destroyed and display also with the new one.

**Comment by bidram** [comment]
> I also had the same issue but adding below entry to the middleware array in Kernel.php:
> 
> protected $middleware = [ \Flasher\Laravel\Middleware\FlasherMiddleware::class, ]
> 
> cause the flash notifications keep displaying anytime, anywhere in my app. Moreover, the old notification are not destroyed and display also with the new one.

Hello

check the .fl-wrapper class in the flash.min.css file. The z-index should be at the highest level so that it does not interfere with the style of your template.
        
My problem is solved and I hope your problem is solved too.

I also had this problem. Go to Kernel.php file
Code snippet below ->
\Flasher\Laravel\Middleware\FlasherMiddleware::class, 

Add to protected $middlewareGroups. ->

    protected $middlewareGroups = [
        'web' => [
            ......
            \Flasher\Laravel\Middleware\FlasherMiddleware::class,

        ],
        'api' => [
            // \Laravel\Sanctum\Http\Middleware\EnsureFrontendRequestsAreStateful::class,
            'throttle:api',
            \Illuminate\Routing\Middleware\SubstituteBindings::class,
        ],
    ];
    

    

    
Thank You

**Comment by yoeunes** [comment]
Hi @krisc78,

I’m currently working on reducing the number of open issues to keep the project organized.

If you’re still experiencing this problem, please update to the latest version of PHPFlasher. If the issue persists, feel free to reopen this issue or open a new one.
