### ISSUE TITLE
Settings

### ISSUE THREAD

**Issue by atadioli** [php-flasher/php-flasher#139]
Hi!
Package very well! ;-)
I use this in my laravel project.
I ask you if is possible configure some parameters for all noty to call. Is there a configuration file for to set, for example, the position or the duration for all notifications?
Thank you!

**Comment by yoeunes** [comment]
Hi @atadioli, thanks for using [PHPFlasher](https://php-flasher.io/library/noty/). I'm glad to hear that it fits your needs.

To customize global configurations for your notifications, follow these simple steps:

1. Execute `php artisan flasher:install`

1. Navigate to `config/flasher_noty.php`

1. Modify global settings by appending desired options under the options array. As an example:

```php
<?php

return [
    'options' => [
        'timeout' => 5000,
        'layout'  => 'topCenter',
    ],
];
```

I hope this helps! Let me know if you have any further questions.

**Comment by atadioli** [comment]
Than you for your support!
But the solution not working.
Work with this options in `config/flasher_noty.php`
```
return [
    'options' => [
        'duration' => 5000,
        'position'  => [
            'x' => 'center',
            'y' => 'top'
        ],
    ],
];
```
And I setup `'default' => 'notyf',` in `config/flasher.php`

Is it correct my solution?

Thank you!

**Comment by yoeunes** [comment]
Hello!

Thank you for your message. It seems that there may be a misunderstanding regarding the adapter being used. The configuration you provided is for the [notyf](https://php-flasher.io/library/notyf/) adapter and not the [noty](https://php-flasher.io/library/noty/) adapter.

Please ensure that you are using the correct adapter based on your needs. If you are indeed using the `notyf` adapter, then the configuration you provided is correct.

The configuration file for `notyf` is located in `config/flasher_notyf.php` and not `config/flasher_noty.php`.

I hope this clears up any confusion. If you have any further questions or concerns, please let me know.

**Comment by atadioli** [comment]
Oh thank you!
Now I understand.
thank you and good work!
