### ISSUE TITLE
[Feature] Preset messages with value substitution

### ISSUE THREAD

**Issue by ToshY** [php-flasher/php-flasher#142]
**Problem**

Currently it's possible to use presets to predefine the message you want to show, however it does not seem to be possible to substitute variables in it.

Take the following example which displays a message to the user with the specific username.

```yaml
flasher:
  # ...
  presets:
    hello_user:
      type: 'success'
      message: 'Welcome back `%%s`' #needs double percentage sign for YAML
      options:
        toast: true
        position: bottom-end
        showConfirmButton: false
        timer: 5000
```

This would now display "Welcome back \`%s\`" as there does not seem to be a way to pass certain variables to be substituted for the message to `addPreset`.

The workaround for this would be removing the `message` key from the YAML preset and use `setMessage` method to substitute the variable in the message:

```php
$userName = 'John';

// Shows toast with the message: "Welcome back `John`"
flash()->addPreset('hello_user')->setMessage(
    sprintf('Welcome back `%s`', $userName)
);
```

While this is doable, I think it would improve the usability of presets if support is added for basic substitute/replacement of values in the message text.

**Proposal**

Maybe updating the `addPreset` (and deprecated `preset`) method in the `NotificationBuilder` with additional `values` (open to better naming suggestion) array argument where you can pass a flat array of values. The `PresetStamp` would get another property `values`, which then can be used in the `PresetListener` by using sprintf with the splat operator [^1] for substition.

Example:

<details>
<summary><code>PresetStamp</code></summary>

```php
<?php

/*
 * This file is part of the PHPFlasher package.
 * (c) Younes KHOUBZA <younes.khoubza@gmail.com>
 */

namespace Flasher\Prime\Stamp;

final class PresetStamp implements StampInterface
{
    /**
     * @var string
     */
    private $preset;

    /**
     * @var array<string, mixed>
     */
    private $parameters;

    /**
     * @var array<string>
     */
    private $values;

    /**
     * @param string               $preset
     * @param array<string, mixed> $parameters
     * @param array<string>        $values
     */
    public function __construct($preset, array $parameters = array(), array $values = array())
    {
        $this->preset = $preset;
        $this->parameters = $parameters;
        $this->values = $values;
    }

    /**
     * @return string
     */
    public function getPreset()
    {
        return $this->preset;
    }

    /**
     * @return array<string, mixed>
     */
    public function getParameters()
    {
        return $this->parameters;
    }

    /**
     * @return array<string>
     */
    public function getValues()
    {
        return $this->values;
    }
}
```

</details>

<details>
<summary><code>PresetListener</code></summary>

```php
<?php

/*
 * This file is part of the PHPFlasher package.
 * (c) Younes KHOUBZA <younes.khoubza@gmail.com>
 */

namespace Flasher\Prime\EventDispatcher\EventListener;

use Flasher\Prime\EventDispatcher\Event\PersistEvent;
use Flasher\Prime\Exception\PresetNotFoundException;
use Flasher\Prime\Notification\Envelope;
use Flasher\Prime\Stamp\PresetStamp;

/**
 * @phpstan-type PresetType array{
 *    string: array{
 *      type: string,
 *      title: string,
 *      message: string,
 *      options: array<string, mixed>,
 *    }
 * }
 */
final class PresetListener implements EventSubscriberInterface
{
    /**
     * @phpstan-var PresetType[]
     */
    private $presets = array();

    /**
     * @phpstan-param PresetType[] $presets
     */
    public function __construct(array $presets)
    {
        $this->presets = $presets;
    }

    /**
     * @return void
     *
     * @throws PresetNotFoundException
     */
    public function __invoke(PersistEvent $event)
    {
        foreach ($event->getEnvelopes() as $envelope) {
            $this->attachPresets($envelope);
        }
    }

    /**
     * {@inheritdoc}
     */
    public static function getSubscribedEvents()
    {
        return 'Flasher\Prime\EventDispatcher\Event\PersistEvent';
    }

    /**
     * @return void
     *
     * @throws PresetNotFoundException
     */
    private function attachPresets(Envelope $envelope)
    {
        $presetStamp = $envelope->get('Flasher\Prime\Stamp\PresetStamp');
        if (!$presetStamp instanceof PresetStamp) {
            return;
        }

        if (!isset($this->presets[$presetStamp->getPreset()])) {
            throw new PresetNotFoundException($presetStamp->getPreset(), array_keys($this->presets));
        }

        $preset = $this->presets[$presetStamp->getPreset()];
        $preset = array_merge(array(
            'type' => 'info',
            'title' => null,
            'message' => null,
            'options' => array(),
        ), $preset);

        if (null === $envelope->getType()) {
            $envelope->setType($preset['type']);
        }

        if (null === $envelope->getTitle()) {
            $envelope->setTitle($preset['title']);
        }

        if (null === $envelope->getMessage()) {
            $message = $preset['message'];
            if (false === empty($presetStamp->getValues())) {
                $message = sprintf($message, ...$presetStamp->getValues());
            }
            $envelope->setMessage($message);
        }

        $options = array_merge($preset['options'], $envelope->getOptions());
        $envelope->setOptions($options);
    }
}
```
</details>

It would require to update both `addPreset` and (deprecated) `preset` methods, after which you then be able to use it like so:

```php
$userName = 'John';

flash()->addPreset('hello_user', [], [$userName]);

// or with names arguments in php 8+
flash()->addPreset('hello_user', values: [$userName]);
```

---

Let me know what you think. I can create the PR myself to implement this feature if the above implementation is agreeable 🙂 

[^1]:  According to the documentation PHP Flasher is compatible with PHP 5.3+, but the splat operator is available from [5.6 onwards](https://www.php.net/manual/en/migration56.new-features.php#migration56.new-features.splat). At the moment I'm not aware if there is a compact alternative for the splat operator to make it 5.3-5.5 compatible. Open to feedback.

**Comment by yoeunes** [comment]
Hi @ToshY,

I really appreciate your suggestion of having message placeholders directly in Flasher presets. 
It's a great idea! In fact, a similar approach is already used in PHPFlasher itself for translating messages through the translator system.

Taking your idea into account, I propose the following solution for the `hello_user` message:

```php
# src/Controller/PresetController.php:

$username = 'John';

// Shows toast with the message: "Welcome back `John`"
flash()->addPreset('hello_user', [
    'username' => $username,
]);
```

And in the Flasher configuration:

```yaml
# config/packages/flasher.yaml:

flasher:
  presets:
    hello_user:
      type: success
      message: hello_user
```

You can then register your translation in the following file:

```yaml
# translations/messages.en.yaml

hello_user: Welcome back :username
```

This way, you can easily substitute the `username` placeholder with the desired value when adding the preset. The translation system can also be utilized if needed.

I believe this approach enhances the usability of presets by providing a more flexible and dynamic way to include variables in the messages.

Looking forward to your feedback!

**Comment by ToshY** [comment]
Hey @yoeunes 👋 

I hadn't even thought about using the translations for this 🤯 That's a neet way on how to tackle the problem. I'm happy with using it that way.

One last thing: is this already in the documentation? If not, maybe adding a small (sub)section with an example denoting that translations can be used for this kind of substitution would be nice to have 👍 I don't mind making the PR in the documentation repository 🙂

**Comment by yoeunes** [comment]
I'm happy that this solution works for you. The documentation does not cover this part, so adding a small subsection with an example highlighting the usage of translations for variable substitution would be a great addition. It will provide clear guidance to other users as well. So, +1 for that! 🙏🥰
