### ISSUE TITLE
CSP nonce attribute missing

### ISSUE THREAD

**Issue by xcy7e** [php-flasher/php-flasher#150]
When using `auto_render=true"` it is not possible to use Content-Security-Policy `nonce`-Attributes in the automagically added `<script>`-Tag in the HTML `<head>` tag.

However, one could obviously skip `auto_render` and paste it themself but this would require one to keep in mind updating the manually pasted `<script>`-tag each time the bundle updates, which can be hard in a larger team of devs.
That's why I am wondering if there is any way to add this inline script-tag attribute using `auto_render=true` to use phpflasher on it's best while relying on this rather common Content-Security-Policies.

**Comment by yoeunes** [comment]
Hi @xcy7e 👋,

Thank you for your detailed issue report. You're right, adding `Content-Security-Policy` nonce-Attributes to the automatically added `<script>` tag in the HTML `<head>` tag can be quite beneficial.

A potential solution to this issue can be registering a new event listener which intercepts the `flasher.event_subscriber` event and modifies the HTML response to include the nonce attribute. This can be achieved by leveraging an existing security bundle such as `NelmioSecurityBundle`.

For instance, you could define an event listener service in `services.yaml` like so:

```yaml
App\EventListener\FlasherCspListener:
    arguments:
        - '@nelmio_security.csp_listener'
    tags:
        - { name: flasher.event_subscriber }
        - { name: kernel.event_listener, event: kernel.response, method: onKernelResponse, priority: 1 }
```

Here's an example of how you could implement the `FlasherCspListener` class:

```php
<?php

declare(strict_types=1);

namespace App\EventListener;

use Flasher\Prime\EventDispatcher\EventListener\EventSubscriberInterface;
use Flasher\Prime\EventDispatcher\Event\ResponseEvent as FlasherResponseEvent;
use Nelmio\SecurityBundle\EventListener\ContentSecurityPolicyListener;

class FlasherCspListener implements EventSubscriberInterface
{
    private ?string $nonce = null;

    public function __construct(
        private ContentSecurityPolicyListener $contentSecurityPolicyListener,
    ) {
    }

    public function __invoke(FlasherResponseEvent $event): void
    {
        if ('html' !== $event->getPresenter()) {
            return;
        }

        $response = $event->getResponse();

        $placeHolder = '<script type="text/javascript" class="flasher-js"';

        $insertPosition = strripos($response, $placeHolder);
        if(false === $insertPosition) {
            return;
        }

        $attribute = $this->nonce ? sprintf(' nonce="%s"', $this->nonce) : '';
        $response = str_replace($placeHolder, $placeHolder . $attribute, $response);
        $event->setResponse($response);

        $this->nonce = null;
    }

    public function onKernelResponse(): void
    {
        $this->nonce = $this->contentSecurityPolicyListener->getNonce('script');
    }

    public static function getSubscribedEvents(): string
    {
        return FlasherResponseEvent::class;
    }
}
```

Please let me know if this helps or if you need further assistance.

**Comment by xcy7e** [comment]
This is more than I even hoped for @yoeunes 
Works perfectly.

Thank you!

**Comment by yoeunes** [comment]
That's wonderful news, @xcy7e! I'm glad to hear that the solution worked 🎉
