### ISSUE TITLE
Laravel - not possible to use php-flasher with config:cache

### ISSUE THREAD

**Issue by matus-markusek** [php-flasher/php-flasher#151]
Hello, 
if I use option to config cache files in Laravel (10) (php artisan config:cache), i get error:
`Undefined array key "cdn"`
`[php-flasher/flasher/Plugin/FlasherPlugin.php ])(line 167)`

If I dont use caching for config files, all is working ok.
Can you please look at it. 

Thanks

**Comment by yoeunes** [comment]
Hey Matúš 👋,
Thanks for the heads-up on this issue! 🙏 I'll dive into it this week and see what's going on with the config caching in Laravel 10.

**Comment by Yismen** [comment]
At lines 167 and 168, it tries to assig the `cdn` and `local` keys the scripts, but at that point there is noting in `$config['scripts']`. Shouldnt it be reading from the `$config['root_script]` instead, as provided in the next two lines?

`$config['scripts']['cdn'] = (array) $config['root_script']['cdn'];`
`$config['scripts']['local'] = (array) $config['root_script']['local'];`

**Comment by yoeunes** [comment]
Hey Matúš, Yismen 👋,

I've just pushed `v1.15.3` which should fix the issue, Could you please give it a try and confirm if the issue is resolved on your end? 🛠️

Thanks

**Comment by matus-markusek** [comment]
Hello, I can confirm that the issue is fixed :)
Thanks a lot
