### ISSUE TITLE
How do I override the view

### ISSUE THREAD

**Issue by murrant** [php-flasher/php-flasher#154]
I want to override the view used to create notifications.  I used to be able to do that with a template, but that doesn't work any more.

I don't want to mess with a ton of php code, just override the view is all.

**Comment by yoeunes** [comment]
Hey @murrant 👋, have you by any chance started a pull request or some initial code on this?

**Comment by murrant** [comment]
If you look at the flasher.php config file in that PR, I have default set to template.librenms.  I need to update that :)

**Comment by murrant** [comment]
Looks like I'll just need to downgrade flasher, thanks.
