### ISSUE TITLE
Issue with notification displaying when redirect

### ISSUE THREAD

**Issue by forexknight** [php-flasher/php-flasher#156]
Hi,

I have an issue in my dockerized Laravel 10 app and flasher `1.15.3`. The issue is that notifications are not displayed when I'm using something like this:

```php
    public function customRoute(Request $request): RedirectResponse
    {
        // action
        flash()->addSuccess('Success notification.');

        return redirect()->back();
    }
```

When I'm redirecting notification won't be displayed, but when directly returning view it works. 
It behaves like that because of this part of code in your package:

```php
final class StorageBag implements StorageInterface
{
    /**
     * @var BagInterface
     */
    private $bag;

    public function __construct(BagInterface $bag = null)
    {
        $this->bag = null !== $bag && 'cli' !== \PHP_SAPI ? $bag : new ArrayBag();
    }
```
    
especially this `'cli' !== \PHP_SAPI` because since we are using docker our app is in CLI mode. Can anoyone tell my why this PHP_SAPI check has to be present here?

**Comment by yoeunes** [comment]
Hi @forexknight,

I’m currently working on reducing the number of open issues to keep the project organized.

If you’re still experiencing this problem, please update to the latest version of PHPFlasher. If the issue persists, feel free to reopen this issue or open a new one.
