### ISSUE TITLE
Symfony : flash messages don't show up if I don't use $this->addFlash()

### ISSUE THREAD

**Issue by barberob** [php-flasher/php-flasher#157]
Hello,
I have a problem with php-flasher used with symfony :
Flash message don't work until i manually add a dumb flash message in the flashBag with symfony's `$this->addFlash()`.
For exemple, this don't do anything : 
```PHP
#[Route('/home', name: 'app_home')]
public function index(): Response
{
    flash('Welcome to your new controller!'); // also don't work with FlasherInterface dependency injection, nothing happens

    return $this->render('home/index.html.twig', [
        'controller_name' => 'HomeController',
    ]);
}
```
While this works great : 
```PHP
public function index(): Response
{
    $this->addFlash('dumb_message', 'This can be anything'); // isn't even used in the template
    flash('Welcome to your new controller!'); // this shows up

    return $this->render('home/index.html.twig', [
        'controller_name' => 'HomeController',
    ]);
}
```
But I noticed that the flash message works if i flash after a form submission ( without using addFlash )
Perhaps, php-flasher messages shows up if i just use the classic symfony `$this->addFlash()` ( but I need to customize some flashes, so i can't use this everywhere )
I tried this with a fresh symfony project ( `symfony new test-php-flasher --version="6.3.*" --webapp` ) with the default php-flasher config files.

**Comment by jvl1v5** [comment]
Hi,

I have the same problem and figured out some behaviors.

In my test --webapp I figured out the following
- if symfony/security-bundle is installed
  - messages only show up if $this->addFlash() is used OR $this->addFlash('','') is called once in a controller (method inside controller class) before using the flash()->... helper method
  - messages show up if a view is rendered or on a view redirected to
- if symfony/security-bundle is NOT installed
  - messages show up using the flash()->... helper (without using $this->addFlash...)
  - in case of redirects the messages only show up, if the controller (method) redirected to calls $this->addFlash('','') once

In my current project messages after redirects only show up if there is $this->addFlash... is called wether security-bundle is installed or not. Couldn't find out the cause yet.

**Comment by yoeunes** [comment]
Hey guys 👋,

I've just pushed v1.15.6 which should fix the issue, Could you please give it a try and confirm if the issue is resolved on your end? 🛠️

```bash
composer require php-flasher/flasher-symfony ^1.15.6
```

Thanks,
Younes

**Comment by jvl1v5** [comment]
Hey Younes,

I just testet the new version in my test app in all the situations described and my current project. All is working fine now! 🥳 
Thank you very much for fixing this issue! 👍 

Regards, Jens

**Comment by barberob** [comment]
Hey, Sorry for the late response.
I also confirm that this fixes the bug for my use case :+1: 

Thanks !
