### ISSUE TITLE
issue with using flash() is that it displays double messages on the view ( Laravel Fortify )

### ISSUE THREAD

**Issue by arewtech** [php-flasher/php-flasher#158]
I have a problem when customizing User Authentication in Laravel Fortify, where the flash messages appear twice instead of once. What is wrong with my code?

```
// if login success redirect to home / dashboard page and show flash message

        Fortify::authenticateUsing(function (Request $request) {
            $user = User::where('email', $request->email)->first();

            if ($user && Hash::check($request->password, $user->password)) {
                flash()->AddSuccess('Welcome, '.$user->name);
                return $user;
            }
            flash()->addError('Invalid credentials');
        });
```
<img width="766" alt="image" src="https://github.com/php-flasher/php-flasher/assets/75215687/3c20b44e-5363-4c1b-9787-47db0177a5b1">

**Comment by codebyshami** [comment]
Did you solved this error yet?

**Comment by arewtech** [comment]
> Did you solved this error yet?

No, and I've made the decision not to use it

**Comment by yoeunes** [comment]
Hey guys 👋,

Thank you for reporting the issue, I've looked into this, and it seems to be a known issue within Laravel Fortify itself, as discussed here https://github.com/laravel/fortify/issues/339.

As a workaround, you can modify the `FortifyServiceProvider` to ensure that flash messages are only added once during the authentication process. Here's a simple way to implement this:

```php
class FortifyServiceProvider extends ServiceProvider
{
    protected $isFirstCall = true;

    public function boot(): void
    {
        Fortify::authenticateUsing(function (Request $request) {
            $user = User::where('email', $request->email)->first();

            if ($user && Hash::check($request->password, $user->password)) {
                if ($this->isFirstCall) {
                    $this->isFirstCall = false;
                    flash()->addSuccess('Welcome, '. $user->name);
                }

                return $user;
            }

            if ($this->isFirstCall) {
                flash()->addError('Invalid credentials');
            }
        });

        // ... rest of the boot method ...
    }
}
```

In this code, a flag `$isFirstCall` is used to check if it's the first time the authentication method is being called, and the flash message is only added in this instance. This should prevent the flash message from appearing twice.

I hope this helps. Please let me know if you have any further questions.

Best regards,
Younes

**Comment by arewtech** [comment]
> Hey guys 👋,
> 
> Thank you for reporting the issue, I've looked into this, and it seems to be a known issue within Laravel Fortify itself, as discussed here [laravel/fortify#339](https://github.com/laravel/fortify/issues/339).
> 
> As a workaround, you can modify the `FortifyServiceProvider` to ensure that flash messages are only added once during the authentication process. Here's a simple way to implement this:
> 
> ```
> class FortifyServiceProvider extends ServiceProvider
> {
>     protected $isFirstCall = true;
> 
>     public function boot(): void
>     {
>         Fortify::authenticateUsing(function (Request $request) {
>             $user = User::where('email', $request->email)->first();
> 
>             if ($user && Hash::check($request->password, $user->password)) {
>                 if ($this->isFirstCall) {
>                     $this->isFirstCall = false;
>                     flash()->addSuccess('Welcome, '. $user->name);
>                 }
> 
>                 return $user;
>             }
> 
>             if ($this->isFirstCall) {
>                 flash()->addError('Invalid credentials');
>             }
>         });
> 
>         // ... rest of the boot method ...
>     }
> }
> ```
> 
> In this code, a flag `$isFirstCall` is used to check if it's the first time the authentication method is being called, and the flash message is only added in this instance. This should prevent the flash message from appearing twice.
> 
> I hope this helps. Please let me know if you have any further questions.
> 
> Best regards, Younes

Solved, thanks a lot! 🙇🏻
