### ISSUE TITLE
Flash postion did not work

### ISSUE THREAD

**Issue by urshar** [php-flasher/php-flasher#175]
I have installed the PHP Flasher Laravel with the noti library. I try to set the Position with `->layout('topCenter')`, but it did not work.
I tried with other library like pnotity and tostr. But the same problem. The Position is always top right.

Here an example for my test with the toastr library:
```
session()->flash('success', __('registration.success.registration'));
toastr()->positionClass('toast-top-center');
```
Did I something forgot to do? I use the Version 1.15

Andreas

**Comment by yoeunes** [comment]
Hello @urshar, did you try something like:

```php
noty()
    ->layout('topCenter')
    ->addSuccess(__('registration.success.registration'));
```

**Comment by urshar** [comment]
Hi,

Yes i tried this too, but the results ist the same

**Comment by yoeunes** [comment]
Can you please create a repo where i can reproduce the issue, so i can debug easily

**Comment by urshar** [comment]
I send you an email with an link to my repro

**Comment by yoeunes** [comment]
Hi @urshar,

I’m currently working on reducing the number of open issues to keep the project organized.

If you’re still experiencing this problem, please update to the latest version of PHPFlasher. If the issue persists, feel free to reopen this issue or open a new one.
