### ISSUE TITLE
Version 2 Upgrade on Laravel 11

### ISSUE THREAD

**Issue by AhmedGamal** [php-flasher/php-flasher#176]
I found some issues after the version 2 upgrade on Laravel 11:
- Config inject_assets doesn't affect the rendering.
- Config timeout is no longer working and I have to set it for every request
- The option for replacing Laravel default flash is removed, and can't be changed unlike version 1, while the only way to skip this is by using other flash names except (success, error, warning, and info) which means changing a lot of code for existing apps.
- Changing flash_bag in the config doesn't override the default bags but adds new values to the default array.
- When using the Laravel default flash with the bags (success, error, warning, info) the php-flasher fires after reloading the page (after the flash expires).

If version 2 main concept is to replace the default Laravel flash without an option to disable it, I know that downgrading should be the proper solution but unfortunately, this also will not be a good solution because version 1 with Laravel 11 disables the default flash option entirely and also have to rewrite a lot of code to change it to php-flasher and that why I upgraded to version 2 in the first place.

**Comment by yoeunes** [comment]
Hi Ahmed,

Thank you for your detailed feedback on the upgrade to v2 of PHPFlasher. I truly appreciate the time you took to analyze and list these issues.

I apologize for the inconvenience these issues have caused. It’s clear that the transition could have been smoother. I plan to address these concerns over the weekend.

If you have time and are interested, your contribution to resolving these issues would be awesome.

Best regards,  
Younes

**Comment by yoeunes** [comment]
Hi Ahmed,

I've just released v2.0.1, addressing all the issues you highlighted. Here’s a detailed

summary of the changes:

- Rendering is now correctly handled when `inject_assets` is set to false.
- The global timeout setting now applies to all requests.
- The option to disable default flash replacement can now be controlled by setting `flash_bag` to false.
- The `flash_bag` configuration now properly overrides the default values.

Regarding the behavior of default flash messages in Laravel that require a page redirect or refresh to display, this aligns with Laravel's session flash mechanics. If needed, we can explore adding a specific configuration in PHPFlasher to manage this behavior more effectively.

Thank you once again for your valuable feedback.

Best regards,  
Younes

**Comment by AhmedGamal** [comment]
Hi Younes,

Thank you so much for this release that fixes the addressed issues, now everything is working great for me.

The other issue of the flash message being rendered after the second refresh when we use the default config to replace the default flash system as you said aligns with Laravel's session, I found that the problem is that the response is an instance of the Symfony response, not the Laravel one.

so the session middleware would be 

```
namespace Flasher\Laravel\Middleware;

use Flasher\Laravel\Http\Request;
use Flasher\Laravel\Http\Response;
use Flasher\Prime\Http\RequestExtensionInterface;
use Illuminate\Http\Request as LaravelRequest;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpFoundation\Response as SymfonyResponse;

final readonly class SessionMiddleware
{
    public function __construct(private RequestExtensionInterface $requestExtension)
    {
    }

    public function handle(LaravelRequest $request, \Closure $next): mixed
    {
        $response = $next($request);
        
        if ($response instanceof JsonResponse || $response instanceof SymfonyResponse) {
            $this->requestExtension->flash(new Request($request), new Response($response));
        }

        return $response;
    }
}
```

and of course, changing the response type in the Response file to SymfonyResponse.
```

use Flasher\Prime\Http\ResponseInterface;
use Illuminate\Http\JsonResponse as LaravelJsonResponse;
use Illuminate\Http\Response as LaravelResponse;
use Symfony\Component\HttpFoundation\JsonResponse as SymfonyJsonResponse;
use Symfony\Component\HttpFoundation\Response as SymfonyResponse;

final readonly class Response implements ResponseInterface
{
    public function __construct(private SymfonyResponse|SymfonyJsonResponse $response)
    {
    }
```

Reverting those two files to version 1 can be another solution, I didn't want to make a pull request because I didn't know which one you would recommend according to your coding style and future development plan.

I would be happy to share our thoughts to fix this and find the proper solution.

Best Regards,
Ahmed

**Comment by yoeunes** [comment]
Hi Ahmed,

Thanks for the detailed breakdown and the suggested modifications. I will delve into this tonight or tomorrow to evaluate both your proposed solution and the potential implications of reverting to the version 1 approach.

I’ll keep you posted on my progress and might reach out if I need further input.

Best regards,  
Younes

**Comment by yoeunes** [comment]
Hi Ahmed 👋🏼,

I’ve addressed the issues you mentioned in the latest release. Since everything is working now, I’ll close this issue.

If you have any more problems, feel free to open a new issue.

Thanks 🙏🏼.
