### ISSUE TITLE
A feature request.

### ISSUE THREAD

**Issue by nilotpol8448** [php-flasher/php-flasher#190]
Is it possible to pass these messages by using with() functionality in laravel. I tried using it by the regular method suggested in the document. For some pages it is working well but for some the flash message not showing, in some pages two three messages are showing one below the other even after encasing the flash notifications inside if else statement. I had to use toaster flash message after that. 
Am I doing something wrong or thete is some other issue. Please tell thank you. I used it in laravel 11.

**Comment by yoeunes** [comment]
Hi @nilotpol8448,

I tried to reproduce the problem you're experiencing, but I couldn't replicate it on my end. Here's the code I used for testing:

```php
<?php

declare(strict_types=1);

use Illuminate\Support\Facades\Route;

Route::get('/issues/190', function () {
    flash()->success('Your order has been placed successfully.');
    // Passing another success message with the view
    return redirect('/issues/190/redirect')->with('success', 'Your order will be delivered in 3-5 business days.');
});

Route::get('/issues/190/redirect', function () {
    return view('welcome');
});
```

In this example, I'm using both the `flash()` helper and the `with()` method to pass messages. When I run this code, both flash messages are rendered correctly.

**Could you please provide more details to help me understand and reproduce the issue?**

1. **Code Snippets:**
   - Please share the code where you're adding the flash messages.
   - Include the routes or controller methods where you're using the `with()` method and any other relevant code.

2. **View Files:**
   - How are you displaying the flash messages in your Blade templates?
   - Do you have any conditionals or loops that might affect message rendering?

3. **Configuration:**
   - Are there any custom configurations in your `config/flasher.php` file?
   - Have you modified any middleware or service providers related to PHPFlasher?

4. **Environment Details:**
   - PHPFlasher version:
   - Any other packages that might interfere with flash messaging.

5. **Steps to Reproduce:**
   - Detailed steps I can follow to see the issue on my end.

6. **Additional Information:**
   - Screenshots or error messages, if any.
   - Any browser console errors.

**Next Steps:**

Once I have more information, I'll be better equipped to help you resolve the issue. If it's a bug, I'll work on a fix. If it's a configuration or usage issue, I'll guide you through the necessary steps.

**Comment by yoeunes** [comment]
Hi @nilotpol8448,

I’m currently working on reducing the number of open issues to keep the project organized.

If you’re still experiencing this problem, please update to the latest version of PHPFlasher. If the issue persists, feel free to reopen this issue or open a new one.
