### ISSUE TITLE
Messages are not shown in Laravel project

### ISSUE THREAD

**Issue by alibayat23** [php-flasher/php-flasher#191]
I've created a new PHP/Laravel (8.2/11.0) project and added PHPFlasher to that; But nothing is shown. I've folowed your instructions.
After that, I added toastr javascript library to project. Only javascript version works and PHP version won't.

Could you please help me?

**Comment by yoeunes** [comment]
Hello Ali,

Could you please try registering the `\Flasher\Laravel\Middleware\FlasherMiddleware::class` middleware in your application? You can add it to the `$middleware` array in the `app/Http/Kernel.php` file like this:

```php
<?php

namespace App\Http;

use Illuminate\Foundation\Http\Kernel as HttpKernel;

class Kernel extends HttpKernel
{
    /**
     * The application's global HTTP middleware stack.
     *
     * These middleware are run during every request to your application.
     *
     * @var array<int, class-string|string>
     */
    protected $middleware = [
        // Other middleware...
        \Flasher\Laravel\Middleware\FlasherMiddleware::class,
    ];

    // Other properties and methods...
}
```

This should ensure that the middleware is properly registered and can handle the flash notifications.

If adding the middleware doesn't resolve the issue, please share a project on GitHub where you can reproduce the issue, and I'd be glad to help you fix it.

Looking forward to your feedback!

Best regards,  
Younes

**Comment by italoveloso** [comment]
I was with the same problem. Works fine After register the FlasherMiddleware as @yoeunes suggest.

Thanks!

**Comment by yoeunes** [comment]
Thanks Italo for the feedback! I’m glad the suggestion worked for you.

**Comment by alibayat23** [comment]
Thanks for your reply. But the problem with adding the middleware is that in this way, with every page reguest, the class is called. Thus, it can not be managed to be called in class functions.
I have attached my project. I want the flash message to be called only, for example,  after a button is clicked.

I am appreciate you if take a look at my project and make me a suggestion.

Best regards

[_licenseManager.zip](https://github.com/user-attachments/files/16758559/_licenseManager.zip)

**Comment by sjess** [comment]
Hi, add it to `protected $middlewareGroups = [`

**Comment by yoeunes** [comment]
Hi Ali,

Sorry for the delay in responding, I was ill last week and couldn't get back to you sooner.

Regarding your issue, I believe it's quite similar to a previous one we've encountered. You can check out my response here for more details: https://github.com/php-flasher/php-flasher/issues/188#issuecomment-2304540555.

Here’s the change I suggest:

```php
// Remove FlasherMiddleware from the global middleware stack
protected $middleware = [
    // \Flasher\Laravel\Middleware\FlasherMiddleware::class, 
];

// Add it to the 'web' middleware group instead
protected $middlewareGroups = [
    'web' => [
        \Flasher\Laravel\Middleware\FlasherMiddleware::class, // Add here
    ],
];
```

Could you please apply this change and test it on your side? Let me know if it resolves the issue.

**Comment by yoeunes** [comment]
Hi Ali,

I'm closing this issue now. Please upgrade to the latest version of PHPFlasher. If you still experience this problem after upgrading, please open a new issue.

Thanks.
