### ISSUE TITLE
integrate PHPFlasher with Inertia.js

### ISSUE THREAD

**Issue by aa-hridoy** [php-flasher/php-flasher#194]
class HandleInertiaRequests extends Middleware
{
    public function share(Request $request): array
    {
        return array_merge(parent::share($request), [
            'messages' => flash()->render([], 'array'),
        ]);
    }

Flasher\Prime\Flasher::render(): Argument #1 ($presenter) must be of type string, array given, called in app\Http\Middleware\HandleInertiaRequests.php

**Comment by yoeunes** [comment]
Hello @aa-hridoy Thank you for bringing up this issue! You're right, and I apologize for the confusion in the documentation. The actual method signature for `render` is:

```php
public function render(string $presenter = 'html', array $criteria = [], array $context = []): mixed;
```

So, to resolve the issue, you can use it like this:

```php
<?php
// app/Http/Middleware/HandleInertiaRequests.php

class HandleInertiaRequests extends Middleware
{
    public function share(Request $request): array
    {
        return array_merge(parent::share($request), [
            'messages' => flash()->render('array'),
        ]);
    }
}
```

I'll make sure to update the documentation soon.

**Comment by yoeunes** [comment]
i'm closing this because the documentation is updated
