### ISSUE TITLE
Call to undefined function

### ISSUE THREAD

**Issue by asadghazanfary** [php-flasher/php-flasher#23]
hi

how can i fix this:

`Call to undefined function App\Http\Livewire\Admin\Languages\toastr()`

u get this error when call  this method in livewire render method:

`toastr()->livewire()->addSuccess('notification using toastr library');`

thank you

**Comment by yoeunes-spin** [comment]
Hello @asadghazanfary thanks for using flasher, you just need to require the toastr library for laravel :

```bash
composer require php-flasher/flasher-toastr-laravel
```

**Comment by yoeunes** [comment]
Hello @asadghazanfary thanks for using flasher, you just need to require the toastr library for laravel :

```bash
composer require php-flasher/flasher-toastr-laravel
```

**Comment by asadghazanfary** [comment]
I did that.

But I still get the same error.

**Comment by yoeunes** [comment]
Can you share or create an empty repo where you could reproduce the same error?

**Comment by yoeunes** [comment]
friendly ping @asadghazanfary ^^

**Comment by yoeunes** [comment]
i'll close the issue for now, feel free to open it if you still has the problem
