### ISSUE TITLE
Use Flasher in blade view 

### ISSUE THREAD

**Issue by atoaugustyn** [php-flasher/php-flasher#28]
How can I use flasher in blade view in my laravel?

**Comment by yoeunes** [comment]
Hello @atoaugustyn, 
You have to download PHPFlasher Laravel package, try the following :

```bash
composer require php-flasher/flasher-laravel
```

and add this in your view 👍🏼 
```blade
@flasher_render
```

check the Laravel framework integration page: https://php-flasher.github.io/docs/framework/laravel/

**Comment by atoaugustyn** [comment]
@yoeunes I have done this but how do I show the flasher in the blade view if I don't want to use the controller

**Comment by yoeunes** [comment]
Right now, the only entry point to show notifications is from the controller :( , but it is on my roadmap for the next release

**Comment by atoaugustyn** [comment]
Okay sure but how do I configure the position of the flasher?
`'options' => array(
        'duration' => 3000,
        'dismissible' =>true,
        'ripple' =>true,
        'position' =>    'top' , 'center'`

I tried this but it did not work.

**Comment by yoeunes** [comment]
Can you create a GitHub repository and reproduce your problem ?

**Comment by atoaugustyn** [comment]
Okay sure

**Comment by atoaugustyn** [comment]
@yoeunes Thanks I have been able to position the flasher with css
` .notyf__toast {`
` max-width: 50em !important;`
` position: relative;`
`  bottom: 800px !important;
        }`

**Comment by yoeunes** [comment]
Cool, I'm happy you found a solution.
But how did you show the notification from your JavaScript code ?

**Comment by atoaugustyn** [comment]
Right now am using controller to show the notification

**Comment by yoeunes** [comment]
Okey, if you ever found a simple solution from JavaScript, please let me know
