### ISSUE TITLE
Single quotes are escaped

### ISSUE THREAD

**Issue by Mythos** [php-flasher/php-flasher#29]
**Describe the bug**
Single quotes in messages are being escaped and not displayed properly.

This happens due to the `addslashes($messages)` in `NotificationBuilder.php` when calling `message($message)`.

**To Reproduce**
Add a flash notification containing a single quote in the message.

**Expected behavior**
Single quotes being displayed properly.

**Screenshots**
![grafik](https://user-images.githubusercontent.com/416568/152044231-81e4eb84-22f4-4b31-a61e-b5cb8fcab693.png)

**Comment by yoeunes** [comment]
Hello @Mythos, thanks for reporting the issue.
Right now I don't have time to fix the issue, but I will try to fix it soon.

**Comment by Mythos** [comment]
This issue has been fixed with #33.
