### ISSUE TITLE
How to get web push notifications?

### ISSUE THREAD

**Issue by rirri93** [php-flasher/php-flasher#36]
Hi,
php-flasher documentation says that I can send desktop notification for all the OSs, but does not explain how I can do it. Can you explain it here? 
Thanks

**Comment by yoeunes** [comment]
Hello @rirri93,

Yes, you are right, the documentation is not complete yet, and the development is still in progress.
You could check the code in GitHub here: https://github.com/php-flasher/php-flasher/tree/main/src/Cli (READ ONLY)

Or in theirs respective repositories:


- https://github.com/php-flasher/flasher-cli
- https://github.com/php-flasher/flasher-cli-laravel
- https://github.com/php-flasher/flasher-cli-symfony

The notifications are sent from the terminal, inject the `CliFlasherInterface` service in your commands and call the `render` method on it, and that's it.

_I hope someone could help with a PR on the documentation for this part_
