### ISSUE TITLE
Not displayed after redirect from livewire component

### ISSUE THREAD

**Issue by willvincent** [php-flasher/php-flasher#40]
**Describe the bug**
If a redirect is triggered from within a livewire component, the flasher output is never displayed as the request that would have triggered it originated within a livewire component, and the does not appear to be any mechanism available to delay the display until a future request in that case.

Whereas it is otherwise possible to define hops or delay stamps this does not appear to be possible from within a livewire component.

As a redirect causes a page reload, and as best I can tell presently display of flasher messages that originate within a livewire component occur as _events_ rather than being added to the message bag in the session, the is presently no way to display a message after redirect.

**To Reproduce**
1. Add a flasher message within a livewire component, and then redirect to a different page, observe no message displayed
2. Add a flasher message within a livewire component and do NOT redirect, and observe message IS displayed

**Expected behavior**
I expect the notification to display _after_ redirect, even if that requires me adding an extra flag when defining the message, so that for example when saving an entity and then redirecting to a list view - the save message is properly displayed. 

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser Firefox
 - Version 100

**Comment by yoeunes** [comment]
Hello @willvincent thanks for the details.
I just pushed the v1.0.4 which solve this redirection problem, can you check please ?

```
 php-flasher/flasher-laravel
```

**Comment by yoeunes** [comment]
you're welcome ^^
