### ISSUE TITLE
Flasher is not working in Store, Update or Delete functions, but working in Index function ?

### ISSUE THREAD

**Issue by ravindra135** [php-flasher/php-flasher#68]
Hello Sir,

Working in Index Method :
```php
    public function index(FlasherInterface $flasher)
    {
        $users = User::all();
        $flasher->addSuccess('Welcome To Users Section');
        return view('admin.users.index', compact('users'));
    }
```

But not working in :
```php
    public function destroy(FlasherInterface $flasher, User $user)
    {
        $user->delete();
        $flasher->addSuccess('User Deleted!');
        return redirect()->back();
    }
```

What is the reason, Am I doing anything wrong ?

laravel framework = 9.11
package = 1.4.0

**Comment by yoeunes** [comment]
Hello @ravindra135, Thanks for reporting the issue.
I will look at it in a moment

**Comment by yoeunes** [comment]
Hello again, can you please upgrade **PHPFlasher** to v1.5.2, this will fix the issue.
And thank you again for your help

**Comment by ravindra135** [comment]
hey! @yoeunes Thank you so much,  I have updated to the version to  1.5.2, Now its working fine,
