### ISSUE TITLE
Use Blade to create a custom notification theme

### ISSUE THREAD

**Issue by salmayno** [php-flasher/php-flasher#73]
<div style="max-width: 100vw; position: fixed; left: 0; right: 0; top: 0; bottom: 0; background: #4ADE80; width: 100vw; height: 100vh; z-index: 100; margin-left: auto; margin-right: auto; display: flex; justify-content: center; align-items: center;">
    <div>
        <p style="margin-top: 1rem;">Hi, first of all I want to thank you for this great <a href="https://php-flasher.io/">Package</a>, it helped me a lot with creation notification very easily.</p>

        <p style="margin-top: 1rem;">I has a set of themes to displays custom notifications, for instance the user can customize the colors, width and icons for his preferred notification style, I store this preferences in the database and then create creation my notification with a Blade template.</p>
        
        <p style="margin-top: 1rem;">How I can create my notification theme with **Blade** and then show this theme for the user ?</p>
        
        <p style="margin-top: 1rem;">Thanks in advance for your help.</p>
    </div>
</div>

**Comment by yoeunes** [comment]
Hi @salmayno, thanks for using PHPFlasher.

Thanks for your kind words, can you please update the description of the issue, I think it's a great idea to let the user update his preferences.

You could store your blade template like a normal template in the `resources/views` directory, and then you could update the PHPFlasher configuration as follows : 

```php
// config/flasher.php

return [
    'default' => 'flasher',

   'themes' => [
        'flasher' => [
             'view' => 'flasher.blade.php', // here put the path of your template
        ],
   ],
];
```
