### ISSUE TITLE
Livewire using main flasher

### ISSUE THREAD

**Issue by jonathanoeijoeng** [php-flasher/php-flasher#78]
Thanks for creating this awesome alert.
I saw in docs that livewire can only use toastr or sweetalert?
Is it possible to use the main flasher (the one with white background and left border color) ?

thanks

**Comment by yoeunes** [comment]
Hello Jonathan, thanks for your words.
Yes, you can use the `main` flasher just use the `flash()` helper method : 



```php
namespace App\Http\Livewire;

use Livewire\Component;

class MyComponent extends Component
{
    public function someAction()
    {
        flash()->addSuccess('notification using flasher theme');
    }

    public function render()
    {
        return view('livewire.my_component');
    }
}
```
