### ISSUE TITLE
How can i move the flash-toastr.min.js file for flasher-toastr-laravel from cdn to local

### ISSUE THREAD

**Issue by wcaaan** [php-flasher/php-flasher#84]
Hey,

First of all amazing package and very nice work. I can find the config file for ```flasher-laravel``` and i can override the js file there but how do i move the js file of this adapter "flasher-toastr-larave" from cdn to local.

Thankyou

**Comment by yoeunes** [comment]
Hello @wcaaan thanks for your words.

You could either download the **cdn** and copy it somewhere in the public folder, or use **npm** 

```bash
npm i @flasher/flasher
```

here is a link in the doc : https://php-flasher.io/docs/framework/javascript/

**Comment by wcaaan** [comment]
thank you

**Comment by wcaaan** [comment]
I copied the flasher.min.js to public folder and override the root_script with the public folder file, that is working fine but 
```flasher-toastr.min.js``` is still called from cdn, i don't know why

**Comment by wcaaan** [comment]
would'nt it be better if there was a config file for adapter as well ? so if anyone can override the root_script ?

**Comment by yoeunes** [comment]
Yes you have to the same for `flasher-toastr.min.js`, just create a `config/flasher_taostr.php` config file, and put this : 

```php
// config/flasher_toastr.php

return [
    'scripts' => [
         // path to the flasher-toastr.min.js
    ],
];
```
don't forget to add `jquery` as well for `toastr` to work correctly

**Comment by yoeunes** [comment]
check this : https://github.com/php-flasher/php-flasher/blob/main/src/Toastr/Prime/ToastrPlugin.php

**Comment by wcaaan** [comment]
Awesome, thankyou. also can you please tell me how can i pass the flasherInterface from view to show my validation errors, i tried checking out the blade documentation but its empty. appreciate the help.

**Comment by yoeunes** [comment]
Hello @wcaaan sorry for the late response.
I will answer you on the other issue : https://github.com/php-flasher/php-flasher/issues/86

**Comment by wcaaan** [comment]
No worries.
