### ISSUE TITLE
laravel 9 installed but missing config/flasher.php

### ISSUE THREAD

**Issue by junglebookDevTeam** [php-flasher/php-flasher#85]
terminal outputs

$ composer require php-flasher/flasher-laravel

Info from https://repo.packagist.org: #StandWithUkraine
Using version ^1.7 for php-flasher/flasher-laravel
./composer.json has been updated
Running composer update php-flasher/flasher-laravel
Loading composer repositories with package information
Updating dependencies
Lock file operations: 2 installs, 0 updates, 0 removals
  - Locking php-flasher/flasher (v1.7.0)
  - Locking php-flasher/flasher-laravel (v1.7.0)
Writing lock file
Installing dependencies from lock file (including require-dev)
Package operations: 2 installs, 0 updates, 0 removals
  - Downloading php-flasher/flasher (v1.7.0)
  - Downloading php-flasher/flasher-laravel (v1.7.0)
  - Installing php-flasher/flasher (v1.7.0): Extracting archive
  - Installing php-flasher/flasher-laravel (v1.7.0): Extracting archive
Generating optimized autoload files
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover --ansi
Discovered Package: laravel/sail
Discovered Package: laravel/sanctum
Discovered Package: laravel/tinker
Discovered Package: milon/barcode
Discovered Package: nesbot/carbon
Discovered Package: nunomaduro/collision
Discovered Package: php-flasher/flasher-laravel
Discovered Package: realrashid/sweet-alert
Discovered Package: spatie/laravel-ignition
Package manifest generated successfully.
83 packages you are using are looking for funding.
Use the `composer fund` command to find out more!
> @php artisan vendor:publish --tag=laravel-assets --ansi --force
No publishable resources for tag [laravel-assets].
Publishing complete.

flasher works fine but, config/flasher.php file is missing in my project folder.

where should I find the file? something I missing?

**Comment by yoeunes** [comment]
Hello @junglebookDevTeam for now you need to create the config file manually in `config/flasher.php`.

You don't need to copy past all the file content, instead just override to config keys you want as the config will be merged with the default one : https://php-flasher.io/docs/laravel/configuration/

```php
<?php
// config/flasher.php

return [

    /*
    |--------------------------------------------------------------------------
    | Default PHPFlasher driver
    |--------------------------------------------------------------------------
    | This option controls the default driver that will be used by PHPFlasher.
    |
    | Supported drivers: "flasher", "toastr", "noty", "sweetalert", "pnotify"
    | 
    | Only "flasher" is supported by default, but you can install other options using composer.
    |
    | "toastr"     : composer require php-flasher/flasher-toastr-laravel
    | "noty"       : composer require php-flasher/flasher-noty-laravel
    | "notyf"      : composer require php-flasher/flasher-notyf-laravel
    | "sweetalert" : composer require php-flasher/flasher-sweetalert-laravel
    | "pnotify"    : composer require php-flasher/flasher-pnotify-laravel
    */
    'default' => 'flasher',
    
    /*
    |--------------------------------------------------------------------------
    | Main PHPFlasher javascript file 
    |--------------------------------------------------------------------------
    | This is the main javascript file that will be included in the page ony
    | when a notification is ready to be displayed, by defaut PHPFlasher
    | use a CDN with the latest version of the library. but you
    | could download it locally or install it with npm.
    */
    'root_script' => 'https://cdn.jsdelivr.net/npm/@flasher/flasher@1.1.0/dist/flasher.min.js',
    
     /*
     |--------------------------------------------------------------------------
     | Translate PHPFlasher messages
     |--------------------------------------------------------------------------
     | By default PHPFlasher messages are passed to Laravel translator service
     | to disable this behavior, set this option to `false`.
     */
    'auto_translate' => true,
    
     /*
     |--------------------------------------------------------------------------
     | Inject PHPFlasher in Response
     |--------------------------------------------------------------------------
     | PHPFlasher scripts are added automatically before </body>, by listening
     | to the Response after the App is done. If you disable this, you
     | have to add them in your template yourself.
     */
    'auto_render' => true,
    
    'flash_bag' => [
        /*
        |-----------------------------------------------------------------------
        | Enable flash bag
        |-----------------------------------------------------------------------
        | This option allows you to automatically convert Laravel's flash
        | messages to PHPFlasher notifications. This is useful when
        | you want to migrate from a Legacy system or another
        | library similar to PHPFlasher.
        */
        'enabled' => true,
        
        /*
        |-----------------------------------------------------------------------
        | Flash bag type mapping
        |-----------------------------------------------------------------------
        | This option allows you to map or convert session keys to PHPFlasher
        | notification types. on the right side are the PHPFlasher types
        | On the left side are the Laravel session keys that you
        | want to convert to PHPFlasher types.
        */        
        'mapping' => [
            'success' => ['success'],
            'error' => ['error', 'danger'],
            'warning' => ['warning', 'alarm'],
            'info' => ['info', 'notice', 'alert'],
        ],
    ],
];
```
