### ISSUE TITLE
Flasher for blade rendering validation errors

### ISSUE THREAD

**Issue by wcaaan** [php-flasher/php-flasher#86]
Hey can you please update the documentation about how to pass the ```flasherInterface``` from view to show my validation errors, i tried checking out the blade documentation but its empty. appreciate the help.

I've created an error blade file which will render my validation errors, for now I'am using ```Flasher Facade```, is there a better way to do this.

```
<?php
	use Flasher\Laravel\Facade\Flasher;
?>
    @if(isset($errors) && count($errors) > 0)
		@foreach($errors->all() as $error)
			<strong>@php Flasher::addError($error) @endphp</strong>
		@endforeach
	@endif
```

**Comment by yoeunes** [comment]
Hi @wcaaan, PHPFlasher does not yet support rendering notifications from blade template with this syntax, but you may use javascript for this, please cheeck this page : https://php-flasher.io/docs/framework/javascript/#-usage

**Comment by wcaaan** [comment]
Okay, Thanks
