### ISSUE TITLE
Icon's background size error

### ISSUE THREAD

**Issue by Kashorako** [php-flasher/php-flasher#91]
**Describe the bug**
Hi guys, the library is great, i'm using this with Tall Stack, the problem occurs when i invoke the flash() from a helper file (i mean i have a file, outside of our components in which i have a lot of functions) one of those functions is used to retrieve some data using SOAP, and i'm trying to display a flash notification when a problem occurs.
The main problem is that the icon's background is not loaded correctly, as you can see in the attached picture
![image](https://user-images.githubusercontent.com/70036607/201720324-fc9a27cf-c9e6-4292-a127-fdbbc49953e7.png)

This is how i invoke the flash()
```
if (count($response->RespuestaCuis->mensajesList) > 1) {
                foreach ($response->RespuestaCuis->mensajesList as $errorMessage) {
                    flash()->addFlash('error', $errorMessage->codigo . ": " . $errorMessage->descripcion, 'Errores al generar el CUIS', ['hops' => 5]);
                }
            } else {
                flash()->addFlash('error', $response->RespuestaCuis->mensajesList->codigo . ": " . $response->RespuestaCuis->mensajesList->descripcion, 'Error al generar el CUIS');
            }
            return false;
```

Thank you so much for your time!

**Comment by yoeunes** [comment]
Hello @Kashorako, thanks for using PHPFlasher and reporting the issue.
Apparently you have some CSS that change the look of the icon, can you reproduce the problem on a GitHub project and share the link please ?

**Comment by Kashorako** [comment]
Hi @yoeunes, thank you so much for your answer. i believe the problem is related with the timing, i mean, the icon starts smaller and once is shown it gets its original size.
As you mention, i;ll try to reproduce the problem on a Github project, in the meantime, is it possible to hide the icon and background?
I can't find that information in the docs.

Thank you so much!
I'll let you know any news

**Comment by yoeunes** [comment]
Hello @Kashorako, 

I just pushed **v1.9.1** of `PHPFlasher` packages which resolves this issue, can you please upgrade your project, and use the latest version of `@flasher` assets

```bash
composer update "php-flasher/*"
```

Then update you `PHPFlasher` package configuration
```bash
php artisan vendor:publish --force --tag=flasher-config
```

If you are using local flasher assets, run :
```bash
php artisan vendor:publish --force --tag=flasher-assets
```

dont forget to set `use_cdn` to false for local assets
