### ISSUE TITLE
Flashes not working with hotwired/turbo

### ISSUE THREAD

**Issue by 24unix** [php-flasher/php-flasher#92]
**Is your feature request related to a problem? Please describe.**
Flashes are not working with turbo enabled.
If I add data-turbo="false" to the body they work like expected.

**Describe the solution you'd like**
I'd like to make use of turbo.

**Describe alternatives you've considered**
Maybe a special div to where the flashes are rendered, so that only that div can be excluded from turbo?

**Comment by yoeunes** [comment]
Hello @24unix thanks for reporting the issue, I never used `hotwired/turbo` before, maybe I will need some help on this issue

**Comment by 24unix** [comment]
@yoeunes Well hotwire keeps track of the headers. The whole body is completely reloaded and turbo manages the updates.

This is where php-flasher injects:
<img width="568" alt="image" src="https://user-images.githubusercontent.com/36622631/202004984-24524016-0881-4817-bbb9-91320b3bba16.png">

Maybe it might be enough to add `data-turbo="false"` to fl-main-container.

**Comment by yoeunes** [comment]
Just add a `<div class="fl-main-container" data-position="top-right'></div>` in your view, and `PHPFlasher` will inject the notification inside that div 

here is why : https://github.com/php-flasher/flasher-js/blob/329cd5398a0a1531c0d453a757cd39d0f2957e11/packages/flasher/src/flasherFactory.ts#L108

let me know if this works for you

**Comment by 24unix** [comment]
Thanks for you fast reply. That sounds reasonable, but didn't work :-(

Turbo seems to re-render that stuff.

<img width="736" alt="image" src="https://user-images.githubusercontent.com/36622631/202166083-ad1ef2c5-0c82-4477-b795-ea61360bc43f.png">

**Comment by yoeunes** [comment]
Can you share a project on GitHub when I can reproduce the issue ?

**Comment by 24unix** [comment]
I don't use GitHub because of MS … But I opened my Repo: https://git.24unix.net/tracer/Spookie
If that won't help, I'll try to clone it on MS GitHub.

**Comment by yoeunes** [comment]
Hello @24unix, can you upgrade to v1.8.0

**Comment by 24unix** [comment]
> Hello @24unix, please upgrade to v1.8.0, and give your feedback if this is fixed or not

Is it already available via composer? It offers me 1,7 as the latest release.

**Comment by 24unix** [comment]
Does not yet seem to work. I'll place a public demonstrator online tomorrow.

**Comment by 24unix** [comment]
Well, I setup a demonstrator, and unlike in my dev environment it works :)

You can check it under
https://spookie.24unix.net/

Login is "micha" password "test12", if you edit the profile and save the flash appears.

Thanks a lot for your help.
