### ISSUE TITLE
Class "Flasher\Prime\Flasher" not found

### ISSUE THREAD

**Issue by a3m-nix** [php-flasher/php-flasher#99]
I got the error "Class "Flasher\Prime\Flasher" not found" in Laravel 9 with the Windows 11 operating system, I think this error is because the Windows operating system cannot have a file with the same name as in the php-flasher package, namely the Flasher file. php and flasher.php, if on linux I don't think there is a problem.

**Comment by yoeunes** [comment]
Hello @a3m-nix, thanks for using `PHPFlasher` and for reporting the issue,
Can you please share a project where this error is happening, or give more details about it?
What are : PHP version, PHPFlasher version?

**Comment by a3m-nix** [comment]
PHP 8.1.6 (cli) (built: May 11 2022 08:55:59) (ZTS Visual C++ 2019 x64)
Copyright (c) The PHP Group
Zend Engine v4.1.6, Copyright (c) Zend Technologies
PHP Flasher  latest version from this https://php-flasher.io/docs/installation/

**Comment by yoeunes** [comment]
Thank you @a3m-nix, I will rename the helper files to `helpers.php`, I will let you know when it's done,
I don't have Windows to test this, thanks in advance

**Comment by yoeunes** [comment]
Can you upgrade to `v1.10.1` and check if the fix works for or not:

```bash
composer update "php-flasher/*"
```

**Comment by a3m-nix** [comment]
it's working fine now, thanks a lot for the help and good response.

**Comment by yoeunes** [comment]
You're welcome, Thanks for the confirmation 🎉
